name:                haskell-project
version:             0.1.0.0
github:              "githubuser/haskell-project"
license:             BSD3
author:              "Chung Wing Poon / Erblin Marku"
maintainer:          "example@example.com"
copyright:           "2021 Chung Wing Poon, Erblin Marku"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A haskell group project for ECS713P 2021/22 

dependencies:
- base >= 4.7 && < 5
- http-conduit
- sqlite-simple
- bytestring
- aeson
- utf8-string
- text
- split
- time
- regex-pcre-builtin
- html-entities
- ansi-terminal

library:
  source-dirs: src

executables:
  haskell-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-project

tests:
  haskell-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-project
